name: Qiskitenv
dependencies:
- python=3.10
- notebook
- matplotlib
- ipywidgets
- pip
- pip:
  - ibm-quantum-widgets~=1.0.3
  - matplotlib~=3.6.1
  - celluloid~=0.2.0
  - ipython~=8.6.0
  - jupyter~=1.0.0
  - qiskit~=0.39.0
  - Pillow~=9.3.0
  - pandas~=1.5.1
  - numpy~=1.23.4
  - numba~=0.56.3
  - tqdm~=4.64.1

